# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nchat.proto\"k\n\x07Mensaje\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x16\n\x0eusernameEmisor\x18\x04 \x01(\t\x12\x18\n\x10usernameReceptor\x18\x05 \x01(\t\"\x1d\n\x0cMensajeReply\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1b\n\x07\x43liente\x12\x10\n\x08username\x18\x01 \x01(\t\"\x07\n\x05Vacio2\xae\x01\n\x04\x43hat\x12\"\n\nChatStream\x12\x06.Vacio\x1a\x08.Mensaje\"\x00\x30\x01\x12*\n\rEnviarMensaje\x12\x08.Mensaje\x1a\r.MensajeReply\"\x00\x12\'\n\x0fListadoClientes\x12\x06.Vacio\x1a\x08.Cliente\"\x00\x30\x01\x12-\n\x13MensajesEnviadosPor\x12\x08.Cliente\x1a\x08.Mensaje\"\x00\x30\x01\x62\x06proto3')
)




_MENSAJE = _descriptor.Descriptor(
  name='Mensaje',
  full_name='Mensaje',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Mensaje.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='Mensaje.mensaje', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Mensaje.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='usernameEmisor', full_name='Mensaje.usernameEmisor', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='usernameReceptor', full_name='Mensaje.usernameReceptor', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=121,
)


_MENSAJEREPLY = _descriptor.Descriptor(
  name='MensajeReply',
  full_name='MensajeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='MensajeReply.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=152,
)


_CLIENTE = _descriptor.Descriptor(
  name='Cliente',
  full_name='Cliente',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='Cliente.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=181,
)


_VACIO = _descriptor.Descriptor(
  name='Vacio',
  full_name='Vacio',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=190,
)

DESCRIPTOR.message_types_by_name['Mensaje'] = _MENSAJE
DESCRIPTOR.message_types_by_name['MensajeReply'] = _MENSAJEREPLY
DESCRIPTOR.message_types_by_name['Cliente'] = _CLIENTE
DESCRIPTOR.message_types_by_name['Vacio'] = _VACIO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Mensaje = _reflection.GeneratedProtocolMessageType('Mensaje', (_message.Message,), {
  'DESCRIPTOR' : _MENSAJE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:Mensaje)
  })
_sym_db.RegisterMessage(Mensaje)

MensajeReply = _reflection.GeneratedProtocolMessageType('MensajeReply', (_message.Message,), {
  'DESCRIPTOR' : _MENSAJEREPLY,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:MensajeReply)
  })
_sym_db.RegisterMessage(MensajeReply)

Cliente = _reflection.GeneratedProtocolMessageType('Cliente', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:Cliente)
  })
_sym_db.RegisterMessage(Cliente)

Vacio = _reflection.GeneratedProtocolMessageType('Vacio', (_message.Message,), {
  'DESCRIPTOR' : _VACIO,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:Vacio)
  })
_sym_db.RegisterMessage(Vacio)



_CHAT = _descriptor.ServiceDescriptor(
  name='Chat',
  full_name='Chat',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=193,
  serialized_end=367,
  methods=[
  _descriptor.MethodDescriptor(
    name='ChatStream',
    full_name='Chat.ChatStream',
    index=0,
    containing_service=None,
    input_type=_VACIO,
    output_type=_MENSAJE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='EnviarMensaje',
    full_name='Chat.EnviarMensaje',
    index=1,
    containing_service=None,
    input_type=_MENSAJE,
    output_type=_MENSAJEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListadoClientes',
    full_name='Chat.ListadoClientes',
    index=2,
    containing_service=None,
    input_type=_VACIO,
    output_type=_CLIENTE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='MensajesEnviadosPor',
    full_name='Chat.MensajesEnviadosPor',
    index=3,
    containing_service=None,
    input_type=_CLIENTE,
    output_type=_MENSAJE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHAT)

DESCRIPTOR.services_by_name['Chat'] = _CHAT

# @@protoc_insertion_point(module_scope)
