version: '3.4'

services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
        RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
        - 5672:5672
        - 15672:15672

  client:
    container_name: client
    build: ./client
    expose: 
      - "5000"
    depends_on:
      - rabbitmq
    volumes:
      - ./client/archivos:/archivos
    privileged: true
    
  server:
    container_name: server
    build: ./server
    expose: 
      - "8001"
    volumes:
      - ./server/archivos:/archivos
    privileged: true

    
  

